server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

management:
  endpoint:
    shutdown:
      enabled: true  
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - shutdown

spring:
  security:
    user:
      name: caru
      password: rudeo512



logging:
  level:
    root: debug
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"    
a: def
