server:
  port: 9001

logging:
  level:
    root: debug
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    
management:
  endpoints:
    web:
      exposure:
        include: refresh
   
spring:     
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
    
a: b
