server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

management:
  endpoints:
    shutdown:
      enabled: true
    web:
      exposure:
        include:
          - refresh
          - shutdown

spring:
  security:
    user:
      name: caru
      password: rudeo512



logging:
  level:
    root: debug
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"    
a: def
